services:
  db:
    image: postgres:17.2-alpine
    container_name: postgres_sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_sql:/var/lib/postgresql/data


volumes:
  pgdata_sql:
